name: untitled
description: "IoT Sensör ve Kontrol Uygulaması - MQTT üzerinden Arduino/ESP ile iletişim"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.1
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
